# Site settings
title: Jack Toumey
email: jack@toumey.io
description: Welcome to my homepage!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
street_address: 1234 Somewhere Road
city: Somewhere
state: CA
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
github_url: https://github.com/miloofcroton
github_username: miloofcroton
pgp_key:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
theme: dimension_jekyll_theme
plugins:
  - jekyll-feed

# Formatting settings
excerpt_separator: <!--more-->
