# Site settings
# accessed via {{ site.title }}, {{ site.email }}, and so on.
title: Jack Toumey
email: jack@toumey.io
description: Welcome to my homepage!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
street_address: 1234 Somewhere Road
city: Somewhere
state: CA
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
github_username: miloofcroton
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
theme: dimension_jekyll_theme
plugins:
  - jekyll-feed
